# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

newyork = Location.create({
  city: 'New York',
  state: 'NY',
  country: 'USA',
  })

User.create([
  {
    email_address: 'albusdumbledore@email.com',
    password: 'password',
    first_name: 'Albus',
    last_name: 'Dumbledore',
    profile_pic: '',
    job_title: 'Headmaster',
    expertiseArray: 'transfiguration,alchemy,occlumency,legilimency,management',
    bio: 'It does not do to dwell on dreams and forget to live.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'minervamcgonagall@email.com',
    password: 'password',
    first_name: 'Minerva',
    last_name: 'McGonagall',
    profile_pic: '',
    job_title: 'Professor',
    expertiseArray: 'transfiguration,animagus,duelling,charms',
    bio: 'I am the Head of Gryffindor House, and a Transfiguration professor.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'serverussnape@email.com',
    password: 'password',
    first_name: 'Serverus',
    last_name: 'Snape',
    profile_pic: '',
    job_title: 'Professor',
    expertiseArray: 'potion,dark arts,occlumency',
    bio: 'I am the Head of Slytherin House, and a Potion professor.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'lordvoldemort@email.com',
    password: 'password',
    first_name: 'Lord',
    last_name: 'Voldemort',
    profile_pic: '',
    job_title: 'The Dark Lord',
    expertiseArray: 'dark arts, duelling,apparition,occlumency,horcruxes,parsel toungue,leadership skills',
    bio: 'I am the Dark Lord and I want to rule the world.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'rubeushagrid@email.com',
    password: 'password',
    first_name: 'Rubeus',
    last_name: 'Hagrid',
    profile_pic: '',
    job_title: 'Professor',
    expertiseArray: 'care of magical creatures, super human strength, gamekeeping',
    bio: 'No good sittin’ worryin’ abou’ it. What’s comin’ will come, an’ we’ll meet it when it does.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'harrypotter@email.com',
    password: 'password',
    first_name: 'Harry',
    last_name: 'Potter',
    profile_pic: '',
    job_title: 'Student',
    expertiseArray: 'duelling,quidditch,expelliarmus spell,defence against the dark arts',
    bio: 'I am famous in the wizarding world.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'hermionegranger@email.com',
    password: 'password',
    first_name: 'Hermione',
    last_name: 'Granger',
    profile_pic: '',
    job_title: 'Student',
    expertiseArray: 'duelling,charms,defence against the dark arts',
    bio: 'I am tenacious and hard-working.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  {
    email_address: 'ronweasley@email.com',
    password: 'password',
    first_name: 'Ron',
    last_name: 'Weasley',
    profile_pic: '',
    job_title: 'Student',
    expertiseArray: 'duelling,defence against the dark arts,quidditch',
    bio: 'I am loyal and funny.',
    linkedin: '',
    github: '',
    personal_website: '',
    mentor_status: true,
    will_buy_coffee: false,
    location_id: 1,
  },
  ])

# raymondholt = User.create(
#   email_address: 'raymond.holt@b99.org',
#   password: 'hi',
#   first_name: 'Raymond',
#   last_name: 'Holt',
#   profile_pic: '',
#   job_title: 'captain',
#   expertiseArray: 'management',
#   bio: 'I am a captain, who is running Precinct 99 in Brooklyn, NY.',
#   linkedin: 'https://linkedin.com/en/raymondholt',
#   github: '',
#   personal_website: '',
#   mentor_status: true,
#   will_buy_coffee: false,
#   location_id: 1,
# )
#
# jakeperalta = User.create(
#   email_address: 'jake.peralta@b99.org',
#   password: 'hi',
#   first_name: 'Jake',
#   last_name: 'Peralta',
#   profile_pic: '',
#   job_title: 'detective',
#   expertiseArray: '',
#   bio: 'Cool cool cool. Coolcoolcoolcool Cooolcool, cool coolcool Coolcoolcoolcool.',
#   linkedin: 'https://linkedin.com/en/jakeperalta',
#   github: '',
#   personal_website: '',
#   mentor_status: true,
#   will_buy_coffee: false,
#   location_id: 1,
# )

# Relationship.create(
#   mentee_id: 1,
#   mentor_id: 2,
#   accepted: true,
# )
#
# Relationship.create(
#   mentee_id: 3,
#   mentor_id: 1,
#   accepted: true,
# )

# Message.create(
#   text: 'Lin to Amy',
#   relationship_id: 3,
#   user_id: 4,
# )
